name: ie-bank-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: talineshawwa-fe-dev
  FRONTEND_WEBAPP_UAT: talineshawwa-fe-uat

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build:dev  ## Build the vue.js app using .env.development into dist-dev/ folder
        env:
          NODE_ENV: development  

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: dist-dev/

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-dev
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: .
  
  build-uat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test (UAT)
        run: |
          npm install
          npm run build:uat ## Ensure this builds the Vue.js app using .env.uat into dist-uat/ folder

      - name: Upload artifact for deployment job (UAT)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist-uat/  

  deploy-uat:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build-uat
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build-uat job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat  

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App - UAT'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: .